HUD code refactoring
LevShisterov/BugfixedHL pull request #10
Opened 2018-09-21 09:14 UTC by tmp64

Valve put all HUD-related headers into hud.h that is included almost everywhere and any slight change to any HUD element class will cause the whole client library to rebuild. That takes quite some time.

I split up hud.h into smaller CHudX.h files, added forward declarations to them in `hud.h` and replaced HUD element variables with smart pointers.

I also renamed cpp files to match the classname and header file name.

2018-09-21 10:22 UTC, LevShisterov requested changes
Hi! A lot of work, thanks!
Currently build server is offline. Have to set it up first.

2018-09-21 10:22 UTC, LevShisterov commented on cl_dll/msvc/client.vcxproj
> +    <PlatformToolset>v141</PlatformToolset>
Should be _xp to be usable in WinXP. You can just revert this change from PR.

2018-09-21 10:22 UTC, LevShisterov commented on cl_dll/hud_redraw.cpp
> -
Intended change?

2018-09-21 11:21 UTC, tmp64 commented on cl_dll/hud_redraw.cpp
> -
Yeah. It's supposed to allow you only increase the FOV but the condition is true only if default_fov = 0. So I just removed it.

2018-09-21 11:22 UTC, tmp64 commented on cl_dll/msvc/client.vcxproj
> +    <PlatformToolset>v141</PlatformToolset>
Ok, I will once MSVS finishes installing.

2018-09-21 11:44 UTC, tmp64 commented on cl_dll/msvc/client.vcxproj
> +    <PlatformToolset>v141</PlatformToolset>
Fixed.

2020-08-04 09:40 UTC, tmp64 commented
I was working with this code structure for almost two years and I came to a conclusion that it isn't very good. While I think it's better than what used to be as every HUD element has its own file, all these CHud*.h/.cpp files in the project root directory make it uncomfortable to browse and look for specific files.

I don't think it should be merged into master.

2020-08-04 09:40 UTC, closed without merging